In [1]:
# Import Packages
import pandas as pd

# Import Custom Modules
import sys
sys.path.append('../scripts') 

from feature_engineering import FeatureEngineering, DefaultEstimator

In [2]:
# Load Data
data = pd.read_csv('../data/data.csv')

# Initialize Feature Engineering
fe = FeatureEngineering(data)

Create Aggregate Features

In [3]:
fe.create_aggregate_features()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,Total_Transaction_Amount,Average_Transaction_Amount,Transaction_Count,Std_Dev_Transaction_Amount
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z,2,0,109921.75,923.712185,119,3042.294251
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z,2,0,109921.75,923.712185,119,3042.294251
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z,2,0,1000.00,500.000000,2,0.000000
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z,2,0,228727.20,6019.136842,38,17169.241610
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z,2,0,228727.20,6019.136842,38,17169.241610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-1000.0,1000,2019-02-13T09:54:09Z,2,0,2438140.00,4255.043630,573,22554.029939
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2019-02-13T09:54:25Z,2,0,58499.60,1360.455814,43,2274.756582
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2019-02-13T09:54:35Z,2,0,58499.60,1360.455814,43,2274.756582
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,UGX,256,ProviderId_6,ProductId_19,tv,ChannelId_3,3000.0,3000,2019-02-13T10:01:10Z,2,0,851985.00,1625.925573,524,3207.920536
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-60.0,60,2019-02-13T10:01:28Z,2,0,851985.00,1625.925573,524,3207.920536

Extract Date-Time Features

In [4]:
fe.extract_datetime_features()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,...,PricingStrategy,FraudResult,Total_Transaction_Amount,Average_Transaction_Amount,Transaction_Count,Std_Dev_Transaction_Amount,Transaction_Hour,Transaction_Day,Transaction_Month,Transaction_Year
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,...,2,0,109921.75,923.712185,119,3042.294251,2,15,11,2018
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,...,2,0,109921.75,923.712185,119,3042.294251,2,15,11,2018
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,...,2,0,1000.00,500.000000,2,0.000000,2,15,11,2018
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,...,2,0,228727.20,6019.136842,38,17169.241610,3,15,11,2018
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,...,2,0,228727.20,6019.136842,38,17169.241610,3,15,11,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,UGX,256,ProviderId_4,ProductId_6,financial_services,...,2,0,2438140.00,4255.043630,573,22554.029939,9,13,2,2019
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,UGX,256,ProviderId_6,ProductId_10,airtime,...,2,0,58499.60,1360.455814,43,2274.756582,9,13,2,2019
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,UGX,256,ProviderId_4,ProductId_6,financial_services,...,2,0,58499.60,1360.455814,43,2274.756582,9,13,2,2019
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,UGX,256,ProviderId_6,ProductId_19,tv,...,2,0,851985.00,1625.925573,524,3207.920536,10,13,2,2019
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,UGX,256,ProviderId_4,ProductId_6,financial_services,...,2,0,851985.00,1625.925573,524,3207.920536,10,13,2,2019

Encode Categorical Variables

In [5]:
fe.encode_categorical_features(method="label")

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,...,PricingStrategy,FraudResult,Total_Transaction_Amount,Average_Transaction_Amount,Transaction_Count,Std_Dev_Transaction_Amount,Transaction_Hour,Transaction_Day,Transaction_Month,Transaction_Year
0,78150,46980,2490,3535,2584,0,256,5,1,0,...,2,0,109921.75,923.712185,119,3042.294251,2,15,11,2018
1,75821,31755,3219,2366,2584,0,256,3,19,2,...,2,0,109921.75,923.712185,119,3042.294251,2,15,11,2018
2,39888,60272,2713,996,2806,0,256,5,0,0,...,2,0,1000.00,500.000000,2,0.000000,2,15,11,2018
3,48738,1797,3351,974,3733,0,256,0,11,8,...,2,0,228727.20,6019.136842,38,17169.241610,3,15,11,2018
4,41364,48941,3219,2366,3733,0,256,3,19,2,...,2,0,228727.20,6019.136842,38,17169.241610,3,15,11,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,88055,92361,3219,2366,1504,0,256,3,19,2,...,2,0,2438140.00,4255.043630,573,22554.029939,9,13,2,2019
95658,89318,46175,2055,1349,2154,0,256,5,1,0,...,2,0,58499.60,1360.455814,43,2274.756582,9,13,2,2019
95659,82370,13891,3219,2366,2154,0,256,3,19,2,...,2,0,58499.60,1360.455814,43,2274.756582,9,13,2,2019
95660,27556,73014,296,3344,521,0,256,5,8,7,...,2,0,851985.00,1625.925573,524,3207.920536,10,13,2,2019
95661,46984,42011,3219,2366,521,0,256,3,19,2,...,2,0,851985.00,1625.925573,524,3207.920536,10,13,2,2019

Handle Missing Values

In [6]:
fe.handle_missing_values(strategy="mean")

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,...,PricingStrategy,FraudResult,Total_Transaction_Amount,Average_Transaction_Amount,Transaction_Count,Std_Dev_Transaction_Amount,Transaction_Hour,Transaction_Day,Transaction_Month,Transaction_Year
0,78150,46980,2490,3535,2584,0,256,5,1,0,...,2,0,109921.75,923.712185,119,3042.294251,2,15,11,2018
1,75821,31755,3219,2366,2584,0,256,3,19,2,...,2,0,109921.75,923.712185,119,3042.294251,2,15,11,2018
2,39888,60272,2713,996,2806,0,256,5,0,0,...,2,0,1000.00,500.000000,2,0.000000,2,15,11,2018
3,48738,1797,3351,974,3733,0,256,0,11,8,...,2,0,228727.20,6019.136842,38,17169.241610,3,15,11,2018
4,41364,48941,3219,2366,3733,0,256,3,19,2,...,2,0,228727.20,6019.136842,38,17169.241610,3,15,11,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,88055,92361,3219,2366,1504,0,256,3,19,2,...,2,0,2438140.00,4255.043630,573,22554.029939,9,13,2,2019
95658,89318,46175,2055,1349,2154,0,256,5,1,0,...,2,0,58499.60,1360.455814,43,2274.756582,9,13,2,2019
95659,82370,13891,3219,2366,2154,0,256,3,19,2,...,2,0,58499.60,1360.455814,43,2274.756582,9,13,2,2019
95660,27556,73014,296,3344,521,0,256,5,8,7,...,2,0,851985.00,1625.925573,524,3207.920536,10,13,2,2019
95661,46984,42011,3219,2366,521,0,256,3,19,2,...,2,0,851985.00,1625.925573,524,3207.920536,10,13,2,2019

Scale Features

In [7]:
fe.scale_features(method="normalize")

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,...,PricingStrategy,FraudResult,Total_Transaction_Amount,Average_Transaction_Amount,Transaction_Count,Std_Dev_Transaction_Amount,Transaction_Hour,Transaction_Day,Transaction_Month,Transaction_Year
0,0.816947,0.495528,0.685573,0.974903,0.690724,0.0,0.0,1.0,0.045455,0.000,...,0.5,0.0,0.557522,0.047184,0.028851,0.000919,0.086957,0.466667,0.909091,0.0
1,0.792601,0.334940,0.886289,0.652510,0.690724,0.0,0.0,0.6,0.863636,0.250,...,0.5,0.0,0.557522,0.047184,0.028851,0.000919,0.086957,0.466667,0.909091,0.0
2,0.416972,0.635727,0.746971,0.274683,0.750067,0.0,0.0,1.0,0.000000,0.000,...,0.5,0.0,0.556944,0.047137,0.000244,0.000000,0.086957,0.466667,0.909091,0.0
3,0.509487,0.018954,0.922632,0.268616,0.997862,0.0,0.0,0.0,0.500000,1.000,...,0.5,0.0,0.558153,0.047749,0.009046,0.005187,0.130435,0.466667,0.909091,0.0
4,0.432402,0.516212,0.886289,0.652510,0.997862,0.0,0.0,0.6,0.863636,0.250,...,0.5,0.0,0.558153,0.047749,0.009046,0.005187,0.130435,0.466667,0.909091,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,0.920490,0.974190,0.886289,0.652510,0.402032,0.0,0.0,0.6,0.863636,0.250,...,0.5,0.0,0.569883,0.047553,0.139853,0.006814,0.391304,0.400000,0.090909,1.0
95658,0.933693,0.487037,0.565804,0.372035,0.575782,0.0,0.0,1.0,0.045455,0.000,...,0.5,0.0,0.557249,0.047233,0.010269,0.000687,0.391304,0.400000,0.090909,1.0
95659,0.861061,0.146517,0.886289,0.652510,0.575782,0.0,0.0,0.6,0.863636,0.250,...,0.5,0.0,0.557249,0.047233,0.010269,0.000687,0.391304,0.400000,0.090909,1.0
95660,0.288059,0.770125,0.081498,0.922228,0.139268,0.0,0.0,1.0,0.363636,0.875,...,0.5,0.0,0.561462,0.047262,0.127873,0.000969,0.434783,0.400000,0.090909,1.0
95661,0.491151,0.443117,0.886289,0.652510,0.139268,0.0,0.0,0.6,0.863636,0.250,...,0.5,0.0,0.561462,0.047262,0.127873,0.000969,0.434783,0.400000,0.090909,1.0

Final dataset

In [8]:
fe.df.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,...,PricingStrategy,FraudResult,Total_Transaction_Amount,Average_Transaction_Amount,Transaction_Count,Std_Dev_Transaction_Amount,Transaction_Hour,Transaction_Day,Transaction_Month,Transaction_Year
0,0.816947,0.495528,0.685573,0.974903,0.690724,0.0,0.0,1.0,0.045455,0.00,...,0.5,0.0,0.557522,0.047184,0.028851,0.000919,0.086957,0.466667,0.909091,0.0
1,0.792601,0.334940,0.886289,0.652510,0.690724,0.0,0.0,0.6,0.863636,0.25,...,0.5,0.0,0.557522,0.047184,0.028851,0.000919,0.086957,0.466667,0.909091,0.0
2,0.416972,0.635727,0.746971,0.274683,0.750067,0.0,0.0,1.0,0.000000,0.00,...,0.5,0.0,0.556944,0.047137,0.000244,0.000000,0.086957,0.466667,0.909091,0.0
3,0.509487,0.018954,0.922632,0.268616,0.997862,0.0,0.0,0.0,0.500000,1.00,...,0.5,0.0,0.558153,0.047749,0.009046,0.005187,0.130435,0.466667,0.909091,0.0
4,0.432402,0.516212,0.886289,0.652510,0.997862,0.0,0.0,0.6,0.863636,0.25,...,0.5,0.0,0.558153,0.047749,0.009046,0.005187,0.130435,0.466667,0.909091,0.0

Initialize Default Estimator with the processed data

In [9]:
de = DefaultEstimator(fe.df)

Compute RFMS Features

In [10]:
rfms_df = de.compute_rfms()
rfms_df.head()

   CustomerId  Recency  Frequency  Monetary  Seasonality
0    0.000000     2148          1  0.090993     0.000000
1    0.000267     2148          1  0.090993     0.000000
2    0.000535     2153          5  0.092279     0.000603
3    0.000802     2090         11  0.091947     0.000052
4    0.001069     2076          6  0.092218     0.000554

Calculate RFMS Score and assign labels

In [11]:
rfms_with_labels = de.calculate_rfms_score()
rfms_with_labels[['CustomerId', 'RFMS_Score', 'Default_Label']].head()

   CustomerId  RFMS_Score Default_Label
0    0.000000       985.5           Bad
1    0.000267       985.5           Bad
2    0.000535      6637.5           Bad
3    0.000802      5401.5           Bad
4    0.001069      8678.5          Good

Visualize RFMS space to establish boundaries

In [12]:
de.plot_rfms_space()

Plot saved as ../data/rfms_space.png

WoE Binning

In [13]:
woe_binned_df, iv_values = de.woe_binning(target_col='Default_Label')
print("Information Values for Features:", iv_values)

Information Values (IV) for features: {'Recency': np.float64(1.5169796182468827), 'Frequency': np.float64(2.42338932928679), 'Monetary': np.float64(1.8459961719565838), 'Seasonality': np.float64(4.2933767539900725)}
Information Values for Features: {'Recency': np.float64(1.5169796182468827), 'Frequency': np.float64(2.42338932928679), 'Monetary': np.float64(1.8459961719565838), 'Seasonality': np.float64(4.2933767539900725)}

../scripts\feature_engineering.py:156: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = self.rfms_df.groupby(binned_col)[target_col].agg(['count', 'sum'])
../scripts\feature_engineering.py:156: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = self.rfms_df.groupby(binned_col)[target_col].agg(['count', 'sum'])
../scripts\feature_engineering.py:156: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = self.rfms_df.groupby(binned_col)[target_col].agg(['count', 'sum'])
../scripts\feature_engineering.py:156: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = self.rfms_df.groupby(binned_col)[target_col].agg(['count', 'sum'])

Build Scorecard

In [14]:
""" scorecard = de.build_scorecard()
scorecard.head() """

' scorecard = de.build_scorecard()\nscorecard.head() '

In [15]:
""" # Save the final scorecard for further analysis or model training
scorecard.to_csv('../data/final_scorecard.csv', index=False)
print("Scorecard saved as 'final_scorecard.csv'")
 """

' # Save the final scorecard for further analysis or model training\nscorecard.to_csv(\'../data/final_scorecard.csv\', index=False)\nprint("Scorecard saved as \'final_scorecard.csv\'")\n '